version: '3.8'
services:
  firebase:
    build: .
    volumes:
      - .:/app  # Mount current directory
      - /app/node_modules  # Isolate modules
    ports:
      - "4000:4000"  # Emulator UI
      - "5001:5001"  # Firestore
      - "8080:8080"  # Hosting
      - "9000:9000"  # Realtime DB
    environment:
      - FIRESTORE_EMULATOR_HOST=0.0.0.0:8080
