# .github/workflows/deploy.yml

name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload site content
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist  # This must match your actual final folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
